CREATE TABLE IF NOT EXISTS student (
    id BIGINT PRIMARY KEY,
    age INTEGER CHECK (age > 15) DEFAULT 20,
    name CHARACTER VARYING(255) UNIQUE NOT NULL
)

CREATE TABLE IF NOT EXISTS faculty (
    id BIGINT PRIMARY KEY,
    color CHARACTER VARYING(255) NOT NULL,
    name CHARACTER VARYING(255) NOT NULL
)

ALTER TABLE faculty ADD CONSTRAINT name_color_unique UNIQUE (name, color)
