CREATE TABLE IF NOT EXISTS human (
    id BIGINT PRIMARY KEY,
    age INTEGER,
    name CHARACTER VARYING(255) NOT NULL,
    hasDriverLicense BOOLEAN DEFAULT false,
    car_id BIGINT REFERENCES car (id)
)

CREATE TABLE IF NOT EXISTS car (
    id BIGINT PRIMARY KEY,
    brand CHARACTER VARYING(255) NOT NULL,
    model CHARACTER VARYING(255) NOT NULL,
    cost NUMERIC CHECK (cost >= 0)
)
